apiVersion: apps/v1
kind: Deployment
metadata:
  name: licensingservice
spec:
  selector:
    matchLabels:
      app: licensingservice
  replicas: 1q
  template:
    metadata:
      labels:
        app: licensingservice
    spec:
      containers:
        - name: licensingservice
          image: johncarnell/tmx-licensing-service:section11
          ports:
            - containerPort: 8080

---

kind: Service
apiVersion: v1
metadata:
  name: licensingservice
spec:
  selector:
    app: licensingservice
  ports:
    - port: 8080
      targetPort: 8080

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: section11-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: www.license.com
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: licensingservice
                port:
                  number: 8080